name: CI/CD
on:
  schedule:
    - cron: '05 11 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}
jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{env.REGISTRY}}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{github.event_name != 'pull_request'}}
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Containerfile
      - name: Sign the published Docker image
        if: ${{github.event_name != 'pull_request'}}
        env:
          TAGS: ${{steps.meta.outputs.tags}}
          DIGEST: ${{steps.build-and-push.outputs.digest}}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
  iso:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora:41
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get year & month
        id: get-ym
        run: |
          echo "ym=$(/bin/date -u '+%Y%m')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache ISO
        id: cache
        uses: actions/cache@v4
        with:
          path: calcite-10.iso
          key: ${{steps.get-ym.outputs.ym}}-${{hashFiles('Containerfile', 'ks.cfg')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: dnf install -y skopeo lorax util-linux
      - name: Download upstream ISO
        if: steps.cache.outputs.cache-hit != 'true'
        run: curl -Lso upstream.iso https://mirror.stream.centos.org/10-stream/BaseOS/x86_64/os/images/boot.iso
      - name: Download container
        run: skopeo copy docker://${{env.REGISTRY}}/${{env.IMAGE_NAME}}:$(git rev-parse --abbrev-ref HEAD) oci:container
      - name: Configure kickstart
        run: sed "s@|CONTAINER_URL|@${CONTAINER_URL}@g" < ks.cfg.in > ks.cfg
        env:
          CONTAINER_URL: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{env.REGISTRY}}/${{env.IMAGE_NAME}}
      - name: Build ISO
        if: steps.cache.outputs.cache-hit != 'true'
        run: mkksiso -a container ks.cfg upstream.iso calcite-10.iso
      - uses: actions/upload-artifact@v4
        with:
          name: iso
          path: calcite-10.iso
      - name: Report status
        run: |
          echo "- Cache hit: \`${{steps.cache.outputs.cache-hit}}\`" >> $GITHUB_STEP_SUMMARY
